easy_admin:
    entities:
        Contact:
            class: App\Entity\Contact
        NewsLetters:
            class: App\Entity\NewsLetters
        Reservations:
            class: App\Entity\Enfants
        CreationAtelier:
            class: App\Entity\CreateAtelier
            list:
                fields:
                    - {property: "image", type: "image", base_path: '/'}
                    - "titre"
                    - {property: "description", type: "text_editor"}
                    - "date"
            form:
                fields:
                    - { property: 'image', type: 'file', type_options: { data_class: null } }
                    - 'titre'
                    - {property: "description", type: "text_editor"}
                    - 'date'

        Ecoles:
            class: App\Entity\School

    site_name: '<img src="/css/images/logokids.png" />'

    design:
        assets:
            css:
                - 'css/admin.css'

        brand_color: '#7fe1fa'